controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

switch_language:
    path: /language/{_locale}
    controller: App\Controller\LanguageController::switchLanguage
    requirements:
        _locale: en|fr  
